### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-cloud-openshift#10]
- [x] Introduction:  Tie OpenShift to Kubernetes in a better way.  This is important.

- [ ] "To login to OpenShift using the CLI, navigate to the online web console > [username] > Copy Login Command > Display Token > Log in with this token." -- I don't think we use monospace style to identify UI menu items.

- [x] "The registry that you will use is called OpenShift Container Registry (OCR), which is OpenShift’s own internal registry which allows a built-in location for you to push images to." -- Double "which" one after another?  Can rephrase.

- [x] "taking the results of the above and manually inputting them into the following docker login command:
docker login -u [oc whoami] -p [oc whoami -t] [oc registry info]"

"taking the results of the above and manually inputting them into the following docker tag commands:"

"taking the results of the above and manually inputting them into the following docker push commands:"

Users should replace what's in square brackets with the right values, right?  If we will do it this way, we should clearly note that they should do so.

- [x] "You can also view the registry address by running the following:" -- Running the following what?

- [x] "The kubernetes.yaml object configuration file is provided for you. If you are interested in learning more about Kubernetes, check out the Deploying microservices to Kubernetes guide." -- Learning more about Kubernetes and its YAML configuration file?

- [ ] "They can also be found in the web console under Networking > Routes > Location." -- Again, style for UI menu items

- Front matter:
  - [x] Ensure that page-duration is accurate;
  - [x] Should have "Red Hat" in either the seo-title or seo-description at the minimum.  Should double check common terms and ensure that we capture them.  Should we include "Java" too?  Refer to the other guides to be consistent too.

I will mark final review as complete.  Can sign off when all the feedback and critical issue(s) have been addressed.

There may be quite some ID edits.  Please plan accordingly.

@MaiHameed @gkwan-ibm

**Comment by MaiHameed** [comment]
Feedback was addressed through commit or moved to a new issue, closing.
