### ISSUE TITLE
ID review feedback

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/draft-guide-cloud-openshift#18]
I'm attaching my feedback for this guide in a Word doc. Please feel free to reach out to me with any questions.

[OpenShift Guide Comments.docx](https://github.com/OpenLiberty/draft-guide-cloud-openshift/files/3580115/OpenShift.Guide.Comments.docx)

After updates have been made, I'll add the ID reviewed label to https://github.com/OpenLiberty/guides-common/issues/189. 

Thanks!!

**Comment by MaiHameed** [comment]
Addressed, thanks @Charlotte-Holt.
