### ISSUE TITLE
Dev Content Review Feedback (2)

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-cloud-openshift#3]
- **What you’ll learn**
  - [x] Look like OpenShift Dedicated is **NOT** Red Hat’s private cloud platform from https://docs.openshift.com
    - either make sure the description of different OC platforms are correct or ask readers to visit https://docs.openshift.com. 
- **Creating a Kubernetes cluster on OpenShift**
  - [x] should we say how the cluster be created more clear?
    - "To create a Kubernetes cluster, you must sign up ..." or
    - "First, you sign up... A Kubernetes cluster will be created when the account is set up."
  - [x] make sure `cluster-id` is the right term
    - my url is https://api.us-west-2.online-starter.openshift.com. "us-west-2" like a region name instead of cluster id
- **Pushing the images to OpenShift’s internal registry**
  - [x] the following command not work in Windows. There may need an OS specific section
    - ``` docker login -u `oc whoami` -p `oc whoami -t` `oc registry info` ``` 
- **Making requests to the microservices**
  - [x] may need to explain what is `system-service` for the following:
    - "Point your browser to the `http://[inventory-hostname]/inventory/systems/system-service` URL. "
- **Tearing down the environment**
  - [x] need an instruction to remove the pushed images on the registry
- ~There is no need to start/stop the local servers~
  - ~[ ] in the finish/pom.xml and start/pom.xml, add following in the  `<configuration/>` of `liberty-maven-plugin`~
    - ~`<skipTestServer>true</skipTestServer>`~

**Comment by MaiHameed** [comment]
Addressed all comments, closing.
