### ISSUE TITLE
Peer Review 

### ISSUE THREAD

**Issue by DannyS03** [OpenLiberty/draft-guide-cloud-openshift#4]
Peer Review: review to be done by a peer member. 

- [x] Check that the guide has working instruction and sample code
- [x] Check the quality of code according to the best coding practices
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Test the guide on 3 platforms: Mac, Win, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable 
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [ ] Define test coverage and review with team (including guide contributor, if available)
- [x] Define detail test cases 
- [x] Consider corner cases targeting the specific guide
- [x] Consider different platform tests, ie, Mac, Windows, Linux
- [x] Consider corner cases UI tests
- [x] Consider testing URL on all browsers, ie, FF, Chrome, Safari
- [x] Consider testing the `curl` command for URL visits
- [x] Consider Consider building with both Maven and Gradle build tools 
- [x] Testing with different IDEs, ie, Atom, VS.code, Eclipse, IntelliJ, Microclimate
- [x] Run Acrolinx Checker on draft (above 70 score approximately)
- [x] Consider SEO title and description for the guides 
- [ ] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [ ] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
- Table of contents 
- Headings
- Paragraphs
- code snippets
- outputs
- links
- hotspots
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases

**Comment by DannyS03** [comment]
Based on team weekly demo 
- Renaming `openshift online` to `openshift` and adjusting summary at the end of the guide 
- Adding content regarding `image-registry` in `kubernetes.yaml`

**Comment by DannyS03** [comment]
**GRAMMER AND WRITING STYLE EDITS**

***What You’ll Learn***

- [ ] Semi-colon `;` instead of comma `,` after OpenShift 
```
You will learn how to deploy two microservices in Open Liberty containers to a built-in Kubernetes cluster on OpenShift, Red Hat’s cloud platform.
```

- [ ] "Tasks that are involved" rather than "tasks involved"
```

 Kubernetes is an open source container orchestrator that automates many tasks involved in deploying, managing, and scaling containerized applications.
```
- [ ] "details that are related" rather than "details related"
```

A cloud-based infrastructure enables you to focus on developing your microservices without worrying about details related to
```
- [ ] 'uses' rather than "will use"
- [ ] 'host' rather than "will host"
- [ ] `public` spelt incorrectly
```
This guide will use OpenShift Online, where you will host your own Kubernetes cluster on Red Hat’s pubilc cloud, and deploy your containerized applications to. 
```

- [ ] 'deploy' rather than "will deploy"
```
The two microservices you will deploy are called system and inventory.
```

- [ ] 'use' rather than "will use"
```
You need a containerization software for building containers. Kubernetes supports various container types, but you will use Docker in this guide.
```

- [ ] 'looks' rather than "will look"
```
The command will look like this:
```

- [ ] "which can be accomplished" rather than "which you can do" 
- [ ] 'prompts' rather than "will promote" 
```
OpenShift will prompt you to create a project, which you can do by simply running the following command:
```

***Deploying microservices to OpenShift***
- [ ] 'learn' rather than "will learn"
```
In this section, you will learn how to deploy two microservices in Open Liberty containers to a Kubernetes cluster on OpenShift.
```

- [ ] 'credential's' instead of 'credentials'
- [ ] 'need' rather than "will need" 
```
However, if you are using a custom credentials store for securing your registry credentials, you will need to use the following command:
```

- [ ] "logged in to" instead of "logged into" 
```
Ensure that you are logged into OpenShift as well as the registry, now run the following commands to tag your applications, remember to substitute [region] and [project-name] with the appropriate values:
```

**Comment by DannyS03** [comment]
**TECHNICAL EDITS**

- [ ] Adding content for `image-registry` regarding the `kubernetes.yaml` file 
```
explanation
```

**Comment by DannyS03** [comment]
- [ ] Time for completion seems to be around 30 minutes

**Comment by DannyS03** [comment]
- `kubernetes.yaml` in the `start` directory does not have hotspot tags like in the `finish` directory

**Comment by DannyS03** [comment]
- Waiting for OpenShift account to be provisioned.

**Comment by NimG98** [comment]
### Prerequisites Section:

- [ ] The steps to install the `oc` CLI, as described by the link ("For installation instructions, refer to the official [OpenShift Online](https://docs.openshift.com/online/getting_started/beyond_the_basics.html#btb-installing-the-openshift-cli) documentation") is different than the actual steps. 

    The steps given say to click "About":

    ![image](https://user-images.githubusercontent.com/46586499/61478664-ef1aa980-a95f-11e9-83f3-facf8f87923c.png)

    However, "About" doesn't show how to install. You actually need to click "Command Line Tools"  to install `oc` CLI: 


    ![image](https://user-images.githubusercontent.com/46586499/61479209-5553fc00-a961-11e9-9c0c-5b5ea62fc559.png)


### Pushing the images to OpenShift’s internal registry

- [ ] I think the part about the "custom credentials store" should be explained more: 

    > First, you must authenticate your Docker client to your OCR. Start by running the login command:
    > ```
    > oc registry login
    > ```
    > However, if you are using a custom credentials store for securing your registry credentials, you will need to use the following command:
    > ```
    > docker login -u `oc whoami` -p `oc whoami -t` `oc registry info`
    > ```

    I thought i didn't have a "custom credentials store", and thought doing the `oc registry login` step was sufficient to authenticate my Docker client. But then the command to push the images wouldn't work (`unauthorized: authentication required`), until i did the `docker login -u oc whoami -p oc whoami -t oc registry info` command.


### Deploying the microservices


- [ ]  `kubernetes.yaml` hotspot in the following line is not going to the file:

    > The `kubernetes.yaml` resource definition file is provided for you


### Making requests to the microservices


- [ ] the hostnames listed here aren't accessible:

    > Your microservices can now be accessed through the hostnames which can be found in the web console under `Networking > Routes > Location`. The hostnames will be formatted like so `inventory-service-[project-name].apps.[region].online-starter.openshift.com`.

    I couldn't access the above url. But I could access the url that was listed on the web console, which started with `inventory-route-...` instead of `inventory-service-...`

    ![image](https://user-images.githubusercontent.com/46586499/61484434-f4cabc00-a96c-11e9-8d7c-ed8b97bc679e.png)


### Testing the microservices


- [ ] the above would also change the `mvn verify` parts to have `inventory-route-...` instead of `inventory-service-...` and `system-route-...` instead of `system-service-...`

    > mvn verify -Ddockerfile.skip=true \
    > -Dsystem.ip=system-service-[project-name].apps.[cluster-ip].online-starter.openshift.com  \
    > -Dinventory.ip=inventory-service-[project-name].apps.[cluster-ip].online-starter.openshift.com


- [ ] `cluster.ip` was never mentioned before in the guide, and is asked to be put into the mvn verify command. 

    > Use the following command to run the integration tests against your cluster. Substitute [cluster-ip] and [project-name] with the appropriate values:
    > ```
    > mvn verify -Ddockerfile.skip=true \
    > -Dsystem.ip=system-service-[project-name].apps.[cluster-ip].online-starter.openshift.com  \
    > -Dinventory.ip=inventory-service-[project-name].apps.[cluster-ip].online-starter.openshift.com
    > ```

    Discussed with Mai, and it should be [region], not [cluster.ip].

**Comment by NimG98** [comment]
- [ ] `diff -r start/ finish/` has an output
    - one big issue is the system and inventory endpoint test files in finish 
    - running `mvn verify` while services are running in finish doesn't work

**Comment by NimG98** [comment]
Tested on Mac, Linux

**Comment by NimG98** [comment]
### Windows

- [ ] This command doesn't work for windows:
    > docker login -u `oc whoami` -p `oc whoami -t` `oc registry info`
- [ ] The `\` causes the command to split in windows, and so copying the command from the button and pasting it into cmd won't work properly:
    > mvn verify -Ddockerfile.skip=true \ \
    > -Dsystem.ip=system-service-[project-name].apps.[cluster-ip].online-starter.openshift.com  \\
    > -Dinventory.ip=inventory-service-[project-name].apps.[cluster-ip].online-starter.openshift.com

**Comment by MaiHameed** [comment]
> **GRAMMER AND WRITING STYLE EDITS**
> 
> * [x]  **Renaming `openshift online` to `openshift` and adjusting summary at the end of the guide**
> 
> _**What You’ll Learn**_
> 
> * [x]  Semi-colon `;` instead of comma `,` after OpenShift
> 
> ```
> You will learn how to deploy two microservices in Open Liberty containers to a built-in Kubernetes cluster on OpenShift, Red Hat’s cloud platform.
> ```
> 
> * [x]  "Tasks that are involved" rather than "tasks involved"
> 
> ```
> 
>  Kubernetes is an open source container orchestrator that automates many tasks involved in deploying, managing, and scaling containerized applications.
> ```
> 
> * [x]  "details that are related" rather than "details related"
> 
> ```
> 
> A cloud-based infrastructure enables you to focus on developing your microservices without worrying about details related to
> ```
> 
> * [ ]  'uses' rather than "will use"
> * [ ]  'host' rather than "will host"
> * [x]  `public` spelt incorrectly
> * [x]  Sentence sounds awkward, consider rewording
> 
> ```
> This guide will use OpenShift Online, where you will host your own Kubernetes cluster on Red Hat’s pubilc cloud, and deploy your containerized applications to. 
> ```
> 
> * [ ]  'deploy' rather than "will deploy"
> 
> ```
> The two microservices you will deploy are called system and inventory.
> ```
> 
> * [ ]  'use' rather than "will use"
> 
> ```
> You need a containerization software for building containers. Kubernetes supports various container types, but you will use Docker in this guide.
> ```
> 
> * [ ]  'looks' rather than "will look"
> 
> ```
> The command will look like this:
> ```
> 
> * [x]  "which can be accomplished" rather than "which you can do"
> * [ ]  'prompts' rather than "will promote"
> 
> ```
> OpenShift will prompt you to create a project, which you can do by simply running the following command:
> ```
> 
> _**Deploying microservices to OpenShift**_
> 
> * [ ]  'learn' rather than "will learn"
> 
> ```
> In this section, you will learn how to deploy two microservices in Open Liberty containers to a Kubernetes cluster on OpenShift.
> ```
> 
> _**Pushing the images to OpenShift’s internal registry**_
> 
> * [ ]  'credential's' instead of 'credentials'
> * [ ]  'need' rather than "will need"
> 
> ```
> However, if you are using a custom credentials store for securing your registry credentials, you will need to use the following command:
> ```
> 
> * [x]  comma `,` after registry
> 
> ```
> The command authenticates you against the internal registry allowing you to then be able to push and pull images. 
> ```
> 
> * [x]  "logged in to" instead of "logged into"
> 
> ```
> Ensure that you are logged into OpenShift as well as the registry, now run the following commands to tag your applications, remember to substitute [region] and [project-name] with the appropriate values:
> ```
> 
> _**Deploying the microservices**_
> 
> * [x]  "address that is used" rather than "address used"
> * [x]  "logged in to" instead of "logged into"
> 
> ```
> The image address used is the OCR address that you logged into, simply update the system image and the inventory image fields to include your project name.
> ```
> 
> * [ ]  "are formatted" instead of "will be formatted"
> 
> ```
> The hostnames will be formatted like so inventory-service-[project-name].apps.[region].online-starter.openshift.com.
> ```
> 
> _**Making requests to the microservices**_
> 
> * [x]  "Ensure that you are" rather of "Ensure you are"
> * [x]  "Upper-left" instead of "top left"
> 
> ```
> Ensure you are in your project, not the default, which is shown in the top left corner of the web console.
> ```
> 
> * [x]  "Properties that are taken" rather than "Properties taken"
> 
> ```
> When you visit this URL, the system properties taken from the system-service are automatically stored in the inventory.
> ```

I refrained from implementing the changes that would change from future tense to present tense as all other guides keep the future tense, and I want to maintain consistency.

**Comment by MaiHameed** [comment]
Addressed all review comments except for one, created a new issue, closing this one.
