### ISSUE TITLE
SME Review

### ISSUE THREAD

**Issue by jkwong888** [OpenLiberty/draft-guide-cloud-openshift#5]
- [x] there seems to be a few cut and paste instances of "Kubernetes cluster on OpenShift".  To be technically correct, OpenShift is a container orchestration platform that is based on Kubernetes, the Kubernetes cluster does not run on top of OpenShift.  Additionally I don't think it's really correct to call it "Red Hat's cloud platform" as it is "Red Hat's container platform", as the intention is that the container platform runs on top of cloud infrastructure.  We should change everywhere it says "Kubernetes cluster on Openshift" to just "Openshift container platform".

- [x] The second paragraph perhaps should expand on what is the difference between OpenShift and Kubernetes.  We mention "A cloud-based infrastructure" but in this case we are actually deploying to managed OpenShift running on likely AWS.  The value proposition of Openshift can be viewed here: https://www.openshift.com/learn/what-is-openshift

- [x] In the Prerequisites section for "OpenShift account", what actually happens beneath the covers is you get access to a managed multi-tenant OpenShift cluster running on AWS.  You do not get your own cluster nor do you get access to their public cloud platform, you are given access to create projects and deploy containers to this cluster.

- [x] it might bear mentioning about the expected outputs of `oc version`, additionally i am not sure of the output before the client is logged in.

- [ ] as mentioned in another guide I reviewed, I don't think this is a very realistic scenario that you have a monolithic build that builds two microservices.  Microservices should be built and deployed separately as building and deploying services together defeats the purpose of having microservices.

- [ ] A little concerning is the security setting on Windows that you advise the user to shut off, where the docker daemon is exposed locally without TLS.  I'd rather have maven not build the image than to shut this off.  Usually a CI process will be building the docker image separately outside of the developer environment anyway.

- [x] for logging into registry part, can you explain more about "custom credentials store".  It's not really clear what this means and whether this applies to me.  For example, i'm pretty sure this applies to mac users as docker integrates with the keychain on mac.

- [ ] As we are building for openshift, one question I had was why we build the docker images locally rather than use any of the openshift s2i developer tools, DeploymentConfigs, or imagestreams.  these are the value propositions of openshift for developers.  For example, we could use a BuildConfig to build the docker image in openshift and not require Docker on the local user's desktop at all.  This would handle building the image and pushing it to the internal registry, and create an ImageStream resource inside of Openshift for tracking.

**Comment by MaiHameed** [comment]
Addressed feedback, moved larger-scale issues to a new issue. Closing.
