### ISSUE TITLE
SME review feedback

### ISSUE THREAD

**Issue by navidsh** [OpenLiberty/draft-guide-cloud-openshift#7]
- [x] "... a built-in Kubernetes cluster **on OpenShift; Red Hat’s cloud platform**." is not very accurate in the following paragraph:
    > You will learn how to deploy two microservices in Open Liberty containers to a built-in Kubernetes cluster on OpenShift; Red Hat’s cloud platform.

    I'd suggest to highlight that OpenShift is basically Kubernetes with some additional tooling and goodies. Once you mention what is OpenShift, then you can refer to it through out the guide. You should be able to find more info about OpenShift from Red Hat's website.
- [x] "...Kubernetes cluster on OpenShift" is also not very accurate. See previous comment.
- [x] "Signing up for an account will automatically provision a single cluster for you to use."
   I am not sure if this is true. My understanding is that OpenShift Online Starter would just give you access to a project to experiment. That doesn't necessarily mean they will provision a dedicated cluster just for one individual. Please correct me if I am wrong.
- [x] I'd suggest to change `oc` to "OpenShift CLI" here:
   > **oc**: You need the OpenShift command-line ...
- [x] It would be good to include what output people should see when they run `oc version` in the following section: 
   > To verify that the OpenShift CLI is installed correctly, run ....
- [x] "Creating a Kubernetes cluster on OpenShift" section needs to be reworded (including title ...) since it is talking about creating a new project in OpenShift and not provisioning a whole new cluster nor creating a Kubernetes cluster on OpenShift.
- [x] Section "Pushing the images to OpenShift’s internal registry": It would be good to mention that OpenShift comes with an internal registry...
- [ ] "MAC" -> "Mac OS X" through out the guide. Mac OS X is the correct name of Mac's operating system.
- [x] Formating "The registry address will be displayed after running the oc registry login command..." -> "The registry address will be displayed after running the `oc registry login` command..."
- [x] "Deploying the microservices" section: "A Kubernetes resource definition is a yaml file that contains a description of all your deployments, services, or any other resources that you want to deploy. ": See the following two links for an overview of K8s objects: [Understanding Kubernetes Objects](https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/#understanding-kubernetes-objects) and [Resources](https://kubectl.docs.kubernetes.io/pages/kubectl_book/resources_and_controllers.html).

**Comment by navidsh** [comment]
I am halfway done with the review. Will review the rest tomorrow.

**Comment by navidsh** [comment]
Thanks @MaiHameed for making the changes. Just a few minor suggestions.

-------

- [ ] "What you’ll learn" section: the second paragraph talks about cloud-based Kubernetes clusters which is a managed service provided by a vendor. In my opinion this information is not relevant.  I'd suggest to shift the focus of this paragraph to OpenShift itself and how is it different from Kubernetes. The following sources my become handy:
  - What is OpenShift? https://www.youtube.com/watch?v=KTN_QBuDplo
  - Kubernetes and OpenShift: What's the Difference? https://www.youtube.com/watch?v=cTPFwXsM2po
  - Red Hat OpenShift overview https://www.youtube.com/watch?v=5dwMrFxq8sU
  - https://www.openshift.com/learn/what-is-openshift
- [ ] "Signing up for an account will automatically **provision a single cluster for you** to use." I don't this is correct. They just allow you to use a multi-tenant cluster and create a project to experiment.
- [ ] I'd suggest to change following paragraph:
> Pushing the images to a registry allows the cluster to create pods by using your container images. The registry that you will use is called OpenShift Container Registry (OCR), which is OpenShift’s own internal registry which allows a built-in location for you to push images to.

to:
   > In order to run the microservices on the cluster, you need to push the microservice images into a container image registry. In this guide you will use OpenShift's integrated container image registry called OpenShift Container Registry (OCR). Once your images are pushed into the registry, you can use them in the pods you create later in the guide.
- [ ] Right after the `docker push` commands and before "Deploying the microservices" section, I'd suggest to add a command to check if the images are pushed properly.  `oc get imagestream` should list the images. Also you can guide people to check the OpenShift's container registry dashboard. I'm not sure if it's available in the OpenShift starter tier.

**Comment by MaiHameed** [comment]
Feedback was addressed or opened in new issues, closing.
