### ISSUE TITLE
User Review

### ISSUE THREAD

**Issue by edavidj** [OpenLiberty/draft-guide-cloud-openshift#8]
Issues:
- Provided instructions all worked smoothly for me. No issues.

Clarity:
- [ ] When applying kubernetes.yaml it could do to emphasize (bold or have it earlier in the paragraph) that you need to swap out [project-name] in the yaml file as at steps like this most will just copy paste and try to move on without reading to the end of the section. Especially for users not familiar with the hotspot feature in these guides.

Misc Suggestions:
- [x] In the section on tagging and pushing images to registry it would save the user some hassle to use ```docker tag system:1.0-SNAPSHOT `oc registry info`/`oc project -q`/system:1.0-SNAPSHOT``` and likewise for the docker push command so that they can just copy paste instead of swapping out the brackets.
- [x] The instructions for going to the route in your browser might benefit slightly from also mentioning you can get the hostnames by using `oc get routes` in the terminal, as it's a little bit faster and consistent across all OpenShift platforms.

**Comment by MaiHameed** [comment]
Ticked off checkboxes applied in referenced commit. Closing.
